services:
  web:
    build: .
    container_name: django-cicd-web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      PYTHONUNBUFFERED: "1"
