# Generated by Django 6.0.5 on 2026-07-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(max_length=20)),
                ('environment', models.CharField(choices=[('Development', 'Development'), ('Staging', 'Staging'), ('Production', 'Production')], default='Development', max_length=20)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Stopped', 'Stopped'), ('Failed', 'Failed'), ('Maintenance', 'Maintenance')], default='Running', max_length=20)),
                ('repository', models.URLField(blank=True)),
                ('deployed_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
